### PR TITLE
PSR Conversion

### LINKED ISSUE #31: [idea] Modify the Luminous codebase to follow PSR standards, be more Composer-compatible, and use PHP 5.3
While working with the Luminous codebase I noticed that It follows quite unusual code conventions, while the most PHP projects follow [the PSR standards](http://php-fig.org/faq/) nowadays. In fact, this is what I got when I first loaded the LaTeX formatter into my highly PSR-optimized editor:
Lots of errors in my editor
There’s a PSR-related error on almost every line of code, or in other words: The Luminous code conventions are really different from what most other projects use.

Now I’d want to know what you’re thinking about modifying the Luminous code to follow those established standards. If you have no objections, I’d be happy to do the actual code change myself. I would also make this package more Composer-compatible and -dependent, since everybody uses this tool now and it makes things a lot easier (no more require statements for every single class to use!). And finally, I’d suggest to drop support for PHP 5.2 and move on to 5.3 since all popular hosting packages support it nowadays (at least I don’t know any package that doesn’t), so we can finally use things like closures :wink:

### PR DESCRIPTION
**Pull request by J5lx**
Hi, it’s me again! After almost one year I finally managed to convince myself of converting the last few files to follow PSR-2 and PSR-4. Please note though that for now I have only converted the codebase of the actual syntax highlighting stuff; I haven’t touched things like docs, tests, and examples. Some other noteworthy aspects:
- The code isn’t well tested yet (mainly because I haven’t converted the tests yet :wink:), but at least basic highlighting via `php luminous.php -f ansi -i src/Luminous.php` is working
- Scanners now need to be autoloadable, but in return this eliminates the need for dependency resolution in `Luminous\Scanners`
- Since PSR-1 requires files not to declare symbols **and** cause side effects (such as `require`ing files) I inlined the function lists in the scanners. I’m still looking for a better solution to this; any ideas are welcome.
- For the same reason `LUMINOUS_VERSION` is now defined in the new file `src/version.php`. The creation of the singleton has also been moved (to `src/singleton.php`)
- Both files as well as `src/debug.php` are now autoloaded on every request by composer. This is suboptimal, and I’d like to eliminate at least the singleton somehow (see also: “[What is so bad about singletons?](http://stackoverflow.com/q/137975/3162530)”)
- I’m not done yet. I’m still in mass editing mode, so I’d like to convert tests, docs and examples as well (in this order). You have to decide whether you want to merge this PR already or leave it open to wait for some more progress.

Resolves #31.

### CODE REVIEW

**Comment by J5lx** [comment]
Oh, one more note: Since the naming conventions changed this breaks BC and needs a major version bump if you adhere to semver.

**Comment by markwatkinson** [comment]
Wow - thanks for this.

There is a lot here and I probably won't get the chance to look through
this until next week, but I will definitely go through it properly next
week, so if you want to keep editing please feel free.

**Comment by markwatkinson** [comment]
I have pulled this into the new 'psr-conversion' branch rather than master, and fixed a couple of very minor things I found.

> Since PSR-1 requires files not to declare symbols and cause side effects (such as requireing files) I inlined the function lists in the scanners. I’m still looking for a better solution to this; any ideas are welcome.

Ok, if I understand this correctly you're referring to the long arrays in the scanners. For example in JavaScanner.php there are about 2.7k lines of keywords/functions/etc. I'm not really happy about this because it makes the code quite unfriendly to work with. 

So, what can we do? 

Let's say we introduce, e.g. JavaScannerData which is a new class that just has a bunch of static properties which are the long array definitions, and then JavaScanner.php `use`s JavaScannerData and accesses its properties. So we keep the long definitions separate from any actual scanning logic. Does that work?

**Comment by J5lx** [comment]
That does in fact sound like a reasonable solution. I personally would go for more specific naming like `XyzKeywords` or something instead of `XyzData`, but that's just preference. However I'd definitely put all those utility classes into their own namespace, `Luminous\Scanners\Keywords` or `Luminous\Scanners\Data` or whatever those classes are going to be named like in the end.

Oh, I'd also go for class constants instead of properties, since those keyword lists are not meant to be modified (they were also immutable even before I touched a single line of the code).

**Comment by markwatkinson** [comment]
Yep - agreed with all of that.

**Comment by J5lx** [comment]
I **finally** got around to doing this - After being on vacation and getting caught up in work afterwards I almost forgot about this. For the moment I had to use a little workaround to make it work in 7.0.0RC2 (`const TYPES= ...` instead of `const TYPES = ...` - pretty weird), but very soon I'm going to check wether that's still needed in RC3.

**Comment by markwatkinson** [comment]
Thanks for doing this, I'll get some time to look at it in the next few days.

 Is the PSR conversion now complete from your perspective?

**Comment by J5lx** [comment]
Yes, I think I’m pretty much done here. However I’d like to do some other stuff as well before this gets incorporated into a new version (e.g. #35, maybe also #33 and the known issues I mentioned in #32).

**Comment by markwatkinson** [comment]
On my machine I am getting a syntax error on some files, e.g.:

```
$ php tests/unit/syntax.php
PHP Fatal error:  Arrays are not allowed in class constants in /home/mark/projects/luminous/src/Luminous/Scanners/Keywords/CKeywords.php on line 63
```

```
$ php -v
PHP 5.5.9-1ubuntu4.11 (cli) (built: Jul  2 2015 15:23:08) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
```

Changing from `const KEYWORDS = array(...` to `static $KEYWORDS = array(` seems to be OK. According to https://stackoverflow.com/questions/1290318/php-constants-containing-arrays const arrays will work since 5.6 so since this is quite easy for us to change I'd prefer to keep compatibility with pre 5.6 versions.

**Comment by J5lx** [comment]
Oh yeah, I forgot about that. I’m almost always using the latest PHP version, and sometimes I lose track of when certain features were introduced.

**Pull request merged**
